export const ActionTypes = {
  // SET_PRODUCTS: "SET_PRODUCTS",
   SET_RECHARGE :"SET_RECHARGE",
  SET_USERS: "SET_USERS",
  SET_USERS_BALANCE: "SET_USERS_BALANCE",
  SET_USERS_EXPENCE: "SET_USERS_EXPENCE",
  FORM_AMOUNT: "FORM_AMOUNT",
  All_FORM:"All_FORM",
 
};
